name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
    - uses: dschep/install-pipenv-action@v1
      with:
        version: 2020.8.13
    - name: Install dependencies
      run: |
        pipenv sync --dev
    - name: Cache result
      uses: actions/cache@v2
      with:
        path: ${{ env.result_json }}
        key: result-json
      env:
        result_json: .products.json
    - name: Lint
      run: |
        pipenv run pylint --rcfile=./pylintrc *.py
    # - name: Main
    #   run: |
    #     pipenv run start "${ARG}"
    #   env:
    #     ARG: ${{ env.result_json }}
